Update release script to cope with several packages

diff --git a/release b/release
--- a/release
+++ b/release
@@ -9,38 +9,61 @@ if [ "$version_response" != "yes" ]; then
     exit 1
 fi
 
-sdist_output=`runghc Setup.lhs sdist`
 
-if [ "$?" != "0" ]; then
-    echo "Cabal sdist failed, aborting"
-    exit 1
-fi
+declare -a subdirectories=( core example hunit quickcheck )
+declare -a filenames
 
-# Want to find a line like:
-# Source tarball created: dist/ansi-terminal-0.1.tar.gz
+index=0
+while [ "$index" -lt "${#subdirectories}" ]; do
+    # Find out the working subdirectory and enter it
+    subdirectory=${subdirectories[index]}
+    cd $subdirectory
 
-# Test this with:
-# runghc Setup.lhs sdist | grep ...
-filename=`echo $sdist_output | sed 's/.*Source tarball created: \([^ ]*\).*/\1/'`
-echo "Filename: $filename"
+    sdist_output=`runghc Setup.lhs sdist`
 
-if [ "$filename" = "$sdist_output" ]; then
-    echo "Could not find filename, aborting"
-    exit 1
-fi
+    if [ "$?" != "0" ]; then
+        echo "Cabal sdist failed, aborting"
+        exit 1
+    fi
 
-# Test this with:
-# echo dist/ansi-terminal-0.1.tar.gz | sed ...
-version=`echo $filename | sed 's/^[^0-9]*\([0-9\.]*\).tar.gz$/\1/'`
-echo "Version: $version"
 
-if [ "$version" = "$filename" ]; then
-    echo "Could not find version, aborting"
-    exit 1
-fi
+    # Want to find a line like:
+    # Source tarball created: dist/ansi-terminal-0.1.tar.gz
 
-echo "This is your last chance to abort! I'm going to upload in 10 seconds"
+    # Test this with:
+    # runghc Setup.lhs sdist | grep ...
+    filename=`echo $sdist_output | sed 's/.*Source tarball created: \([^ ]*\).*/\1/'`
+    filenames[$index]="$subdirectory/$filename"
+    echo "Filename: $filename"
+
+    if [ "$filename" = "$sdist_output" ]; then
+        echo "Could not find filename, aborting"
+        exit 1
+    fi
+
+
+    if [ "$subdirectory" = "core" ]; then
+        # Test this with:
+        # echo dist/ansi-terminal-0.1.tar.gz | sed ...
+        version=`echo $filename | sed 's/^[^0-9]*\([0-9\.]*\).tar.gz$/\1/'`
+        echo "Version: $version"
+
+        if [ "$version" = "$filename" ]; then
+            echo "Could not find version, aborting"
+            exit 1
+        fi
+    fi
+
+
+    # Move to the next directory
+    cd ..
+    let "index = $index + 1"
+done
+
+
+echo "This is your last chance to abort! I'm going to upload v$version in 10 seconds"
 sleep 10
+
 
 git tag "v$version"
 
@@ -49,14 +72,21 @@ if [ "$?" != "0" ]; then
     exit 1
 fi
 
-# You need to have stored your Hackage username and password as directed by cabal-upload
-# I use -v5 because otherwise the error messages can be cryptic :-)
-cabal-upload -v5 $filename
 
-if [ "$?" != "0" ]; then
-    echo "Hackage upload failed, aborting"
-    exit 1
-fi
+index=0
+while [ "$index" -lt "${#filenames}" ]; do
+    # You need to have stored your Hackage username and password as directed by cabal-upload
+    # I use -v5 because otherwise the error messages can be cryptic :-)
+    filename=${filenames[index]}
+    cabal-upload -v5 $filename
+
+    if [ "$?" != "0" ]; then
+        echo "Hackage upload of $filename failed, aborting"
+        exit 1
+    fi
+    
+    let "index = $index + 1"
+done
 
 # Success!
 exit 0
